### ISSUE TITLE
Permitted Users in Contests do not disappear from the list

### ISSUE THREAD

**Issue by enamcse** [RafikFarhad/SUST-Online-Judge#16]
In case of **On Request** contests, the permitted users do not disappear from the list for giving permission in the contest. So, it becomes difficult to find and permit a desired user from the long list. A sample path of the list: https://sustcseoj.com/contest/algo2019_17_2/dashboard/request

**Comment by RafikFarhad** [comment]
Okay. I understand the problem. The matter is that we implement this page for temporary use. It is not wise to display all the users on a single page. But in the beginning, we had a small number of user, so that we provide it for the sake of easiness. We've to figure out a proper way for this process.
Do you have any idea regarding this? 

#salute
#respect
@enamcse

**Comment by RafikFarhad** [comment]
New judge interface does not have this kind of problem.
